name: maza_pandurang
description: "Maza Pandurang - Wari Pilgrimage Management & Service Discovery Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  maplibre_gl: ^0.27.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
